CHAINCODE_ID_NAME={CHAINCODE_ID_NAME}
CHAINCODE_VERSION={CHAINCODE_VERSION}
PEER_ADDRESS={PEER_ADDRESS}
CORE_PEER_ADDRESS=$PEER_ADDRESS CORE_CHAINCODE_ID_NAME=$CHAINCODE_ID_NAME:$CHAINCODE_VERSION CORE_CHAINCODE_LOGGING_LEVEL=debug ./shell-linux
